### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by russellhoff** [DavidBanksNZ/d3-thermometer#3]
Could it be possible to rotate thermometer's orientation from vertical to horizontal?

**Comment by DavidBanksNZ** [comment]
@russellhoff I have never heard of a horizontal thermometer before. Can you show any examples?

**Comment by russellhoff** [comment]
Hi @DavidBanksNZ.

It's just a matter of layout, I'd like to fit it in a rectangular-like card.

**Comment by DavidBanksNZ** [comment]
It's such a rare usage I don't think I'll be adding this feature here, not anytime soon anyway. You could fork the project if you are comfortable working with Javascript and D3.
